car_test:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  throttle_controller:
    type: effort_controllers/JointEffortController
    joint: rear_axel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  steering_controller:
    type: effort_controllers/JointPositionController
    joint: front_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

